parameters:
  env: ''
  artifactName: ''
  serviceConnection: ''
  subscription_id: ''
  tf_rg_name: ''
  tf_rg_location: ''
  tf_sa_name: ''
  tf_sa_sku: ''
  tf_sa_container_name: ''
  environment: ''
  client_id: ''
  client_secret: ''
  tenant_id: ''



steps:
- task: TerraformCLI@0
  displayName: Terraform Plan
  inputs:
    command: plan
    backendType: azurerm
    workingDirectory: $(Build.ArtifactStagingDirectory)/${{ parameters.artifactName }}
    commandOptions: '-var-file= configuration/${{ parameters.env }}.tfvars -var "subscription_id= ${{ parameters.subscription_id }}" -var "client_id= ${{ parameters.client_id }}" -var "client_secret= ${{ parameters.client_secret }}" -var "tenant_id= ${{ parameters.tenant_id }}" -lock=true  -lock-timeout=30s'
    backendServiceArm: ${{ parameters.serviceConnection }}
    backendAzureRmSubscriptionId: ${{ parameters.subscription_id }}
    backendAzureRmResourceGroupName: ${{ parameters.tf_rg_name }}
    backendAzureRmResourceGroupLocation: ${{ parameters.tf_rg_location }}
    backendAzureRmStorageAccountName: ${{ parameters.tf_sa_name }}
    backendAzureRmStorageAccountSku: ${{ parameters.tf_sa_sku }}
    backendAzureRmContainerName: ${{ parameters.tf_sa_container_name }}
    backendAzureRmKey: terraform.tfstate